// Removes unnecessary empty <div> wrappers generated by Webflow Components.
// Safe for CMS and dynamic content. Runs after Webflow fully initializes.

(function () {
  /**
   * Check if a node is a text node containing only whitespace.
   * Used to detect meaningless text content (like line breaks or spaces).
   */
  function isOnlyWhitespace(node) {
    return node.nodeType === Node.TEXT_NODE && !node.textContent.trim();
  }

  /**
   * Check if an element is a <div> with no attributes (no class, id, style, data-, aria-, etc.).
   * These are typical "slot" wrappers generated by Webflow’s component nesting system.
   */
  function isAttrLessDiv(el) {
    return el.tagName === 'DIV' && el.attributes.length === 0;
  }

  /**
   * Performs one cleanup pass:
   * - Removes empty <div> elements.
   * - Unwraps single-child wrappers.
   * Returns true if any DOM modifications were made.
   */
  function cleanOnce(root = document) {
    let changed = false;
    const divs = root.querySelectorAll('div');

    divs.forEach(div => {
      if (!isAttrLessDiv(div)) return;

      const hasElementChildren = div.childElementCount > 0;
      const hasMeaningfulText = Array.from(div.childNodes).some(
        n => n.nodeType === Node.TEXT_NODE && n.textContent.trim().length
      );

      // Remove completely empty <div>s
      if (!hasElementChildren && !hasMeaningfulText) {
        div.remove();
        changed = true;
        return;
      }

      // Flatten single-child wrappers (unwrap child)
      if (div.childElementCount === 1 && !hasMeaningfulText) {
        const onlyChild = div.firstElementChild;
        const parent = div.parentNode;
        if (parent && onlyChild) {
          parent.insertBefore(onlyChild, div);
          div.remove();
          changed = true;
        }
      }
    });

    return changed;
  }

  /**
   * Repeat cleanup until no further changes occur.
   * Ensures deeply nested wrappers are removed as well.
   */
  function cleanDeep(root = document) {
    while (cleanOnce(root)) {}
  }

  /**
   * Wait until Webflow finishes injecting CMS and Components.
   * Runs safely after all layout and interactions are initialized.
   */
  window.Webflow ||= [];
  window.Webflow.push(() => {
    requestAnimationFrame(() => cleanDeep(document));
  });
})();